In [1]:
import cvxpy as cp
import numpy as np
import warnings
import sys
from IPython.core.interactiveshell import InteractiveShell
import torch
import torch.nn as nn
import torch.optim as optim
import time
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
warnings.filterwarnings("ignore")
InteractiveShell.ast_node_interactivity = "all"
sys.path.insert(1,'/Users/dennis/Documents/myGit/main/myUtils')

from torch.utils.data import DataLoader, TensorDataset, random_split
import matplotlib.pyplot as plt

# Generate synthetic data
import genData
import optDatasetRd
import optModelRd

In [2]:
# Generate synthetic data
num_data = 2
num_items = 2
num_features = 5

x, r, c, Q = genData.genDataRd(num_data,num_features, num_items,Q = 100)
alpha = 0.5

In [3]:
r,c

(array([[0.36716864, 0.52770225],
        [0.24030765, 0.5928351 ]]),
 array([[7., 6.],
        [6., 7.]]))

In [4]:
optmodel = optModelRd.optModelRd(num_items,num_data, alpha, Q, r, c)

In [5]:
optmodel.setObj(r,c)
optmodel.solve()

(array([[2.82593417, 5.52884078],
        [2.51779921, 4.56266009]]),
 10.298447263558248)

In [6]:
dataset = optDatasetRd.optDatasetRd(x,r,c,Q,alpha, num_items, num_data)

ValueError: Cannot broadcast dimensions  (2,) (2, 2)

In [ ]:
dataset.opt_objective_values_closed
dataset.opt_objective_values_solver


array([7.49407867, 7.0637668 ])

array([10.59822767,  9.98967479])

In [ ]:
dataset.r[0], dataset.c[0], dataset.Q

(array([0.06787842, 0.69464004]), array([7., 7.]), 100)

In [ ]:
dataset.opt_solutions_closed.shape

(10, 2)

In [ ]:
dataset.opt_objective_values_solver

array([20.87402294, 23.26920956, 25.36608775, 30.26507625, 30.82221381,
       22.3156411 , 28.20809454, 29.54015352, 31.61138626, 23.33006918])

In [ ]:
dataset.opt_objective_values_closed

array([6.60094564, 7.35837016, 8.02146127, 9.57065746, 9.74683982,
       7.05682534, 8.92018272, 9.34141675, 9.99639807, 7.37761566])